name: Other sample action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Creating folder
        run: mkdir Mumbai-Indians/
      - name: Show folder
        run: ls

  Test:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Creating files
        run: echo "Rohit sharma --- Mumbai cha Raja" > /Mumbai-Indians/Mi.txt
      - name: Show file
        run: cat Mi.txt

  Deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: New file
        run: echo "We are the % times title holder" > /Mumbai-Indians/five-times.txt
      - name: Display all files
        run: ls -la
      - name: Show file
        run: cat Mi.txt
        
