name: Other sample action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say CSK
        run: echo "CSK--- Whistle podu" > CSK.txt

      - name: New folder
        run: mkdir Mumbai-Indians/

      - name: Team Mumbai
        run: echo "Duniya hila denge hum" > MI.txt

      - name: Check operating system
        run: uname -a

      - name: Check Linux user
        run: whoami

      - name: Show current directory
        run: pwd

      - name: Show files
        run: ls

      - name: Display file
        run: cat MI.txt
