name: My First GitHub Action

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello i'm Sai Piske-- Here learning github actions" > test.txt

      - name: Check operating system
        run: uname -a

      - name: Check Linux user
        run: whoami
        
      - name: Create file
        run: mkdir piske-folder
             cd piske-folder

      - name: Show current directory
        run: pwd

      - name: Show files
        run: ls -la
